/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as FraisRouteImport } from './routes/frais'
import { Route as FormationsRouteImport } from './routes/formations'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTuitionRouteImport } from './routes/admin.tuition'
import { Route as AdminTextsRouteImport } from './routes/admin.texts'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminProgramsRouteImport } from './routes/admin.programs'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'

const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const FraisRoute = FraisRouteImport.update({
  id: '/frais',
  path: '/frais',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsRoute = FormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTuitionRoute = AdminTuitionRouteImport.update({
  id: '/tuition',
  path: '/tuition',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTextsRoute = AdminTextsRouteImport.update({
  id: '/texts',
  path: '/texts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/equipe': typeof EquipeRoute
  '/formations': typeof FormationsRoute
  '/frais': typeof FraisRoute
  '/galerie': typeof GalerieRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/texts': typeof AdminTextsRoute
  '/admin/tuition': typeof AdminTuitionRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/equipe': typeof EquipeRoute
  '/formations': typeof FormationsRoute
  '/frais': typeof FraisRoute
  '/galerie': typeof GalerieRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/texts': typeof AdminTextsRoute
  '/admin/tuition': typeof AdminTuitionRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/equipe': typeof EquipeRoute
  '/formations': typeof FormationsRoute
  '/frais': typeof FraisRoute
  '/galerie': typeof GalerieRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/texts': typeof AdminTextsRoute
  '/admin/tuition': typeof AdminTuitionRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/admissions'
    | '/contact'
    | '/equipe'
    | '/formations'
    | '/frais'
    | '/galerie'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/programs'
    | '/admin/team'
    | '/admin/texts'
    | '/admin/tuition'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/admissions'
    | '/contact'
    | '/equipe'
    | '/formations'
    | '/frais'
    | '/galerie'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/programs'
    | '/admin/team'
    | '/admin/texts'
    | '/admin/tuition'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/admin'
    | '/admissions'
    | '/contact'
    | '/equipe'
    | '/formations'
    | '/frais'
    | '/galerie'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/programs'
    | '/admin/team'
    | '/admin/texts'
    | '/admin/tuition'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdmissionsRoute: typeof AdmissionsRoute
  ContactRoute: typeof ContactRoute
  EquipeRoute: typeof EquipeRoute
  FormationsRoute: typeof FormationsRoute
  FraisRoute: typeof FraisRoute
  GalerieRoute: typeof GalerieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frais': {
      id: '/frais'
      path: '/frais'
      fullPath: '/frais'
      preLoaderRoute: typeof FraisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations': {
      id: '/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof FormationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tuition': {
      id: '/admin/tuition'
      path: '/tuition'
      fullPath: '/admin/tuition'
      preLoaderRoute: typeof AdminTuitionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/texts': {
      id: '/admin/texts'
      path: '/texts'
      fullPath: '/admin/texts'
      preLoaderRoute: typeof AdminTextsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminTextsRoute: typeof AdminTextsRoute
  AdminTuitionRoute: typeof AdminTuitionRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminTextsRoute: AdminTextsRoute,
  AdminTuitionRoute: AdminTuitionRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRouteWithChildren,
  AdmissionsRoute: AdmissionsRoute,
  ContactRoute: ContactRoute,
  EquipeRoute: EquipeRoute,
  FormationsRoute: FormationsRoute,
  FraisRoute: FraisRoute,
  GalerieRoute: GalerieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
